theme = "catppuccin-mocha"

[editor]
auto-format = true
bufferline = "multiple"
cursorline = true
line-number = "relative"
true-color = true

[editor.lsp]
auto-signature-help = false

[editor.statusline]
left = [ "mode", "spinner", "read-only-indicator", "file-modification-indicator"]
center = [ "file-name" ]
right = [ "selections", "position", "file-encoding", "file-line-ending", "file-type" ]
mode.normal = "NORMAL ğŸ§"
mode.insert = "INSERT ğŸš€"
mode.select = "SELECT  ğŸ‘†"

[editor.cursor-shape]
insert = "bar"
select = "underline"

[editor.indent-guides]
render = true

[keys.normal]
esc = [ "collapse_selection", "keep_primary_selection"]
C-space = "signature_help"
X = "extend_line_up"
C-l = "extend_to_line_end"

[keys.normal.space]
w = ":write"
q = ":quit"
b = ":buffer-close"
